run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/origo-stack/performance-simulator
  govet:
    check-shadowing: true
  misspell:
    locale: US
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  lll:
    line-length: 120

linters:
  enable:
    - bodyclose
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - gochecknoglobals
    - maligned

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goconst
    - path: cmd/
      linters:
        - goconst
  max-issues-per-linter: 0
  max-same-issues: 0
